@screen
Feature: Distributor functionality

  Scenario: Login successful for distributor
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    Then I should see an element with text "Log out"

  Scenario: Login failed for distributor because of wrong password
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "wrongpassword" on textarea with id "password"
    And I click on button with text "Login"
    Then I should see an element with text "Forgot / don't know your password?"

  Scenario: Login failed for distributor because of wrong Email address
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "wrong email address" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    Then I should see an element with text "Forgot / don't know your password?"

  Scenario: Login failed for distributor because he forgot to complete mandatory fields and press Login
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    And I click on button with text "Login"
    Then I should see an element with text "Field cannot be blank"

  Scenario: Forgot password as a distributor
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    And I click on link with text "Forgot / don't know your password?"
    And I type "vescan.remus30+1@gmail.com" into field with id "user_login"
    And I click on input button with text "Get New Password"
    Then I should see an element with text "Request your password"

  Scenario: Applying to be a distributor
    Given I open url "https://dev:J4g^SqXtk%3@staging.fuel-3d.com/"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    And I click on link with text "Apply To Become A Distributor"
    And I type "Remus" into "First Name *" field
    And I type "Vescan" into "Surname *" field
    When I type "vescan.remus30+401@gmail.com" into field with id "email2"
    And I type "remussic" into field with id "password2"
    And I select "Cuba" from dropdown menu with name "country"
    And I type "un text cu orice " on textarea with id "why"
    And I click on button with text "Apply"
    And I wait 50 seconds

  Scenario: A user that applies to become a distributor leaves empty (the) First Name field
    Given I open url "https://dev:J4g^SqXtk%3@staging.fuel-3d.com/"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    And I click on link with text "Apply To Become A Distributor"
    And I type "Vescan" into "Surname *" field
    When I type "vescan.remus30+401@gmail.com" into field with id "email2"
    And I type "remussic" into field with id "password2"
    And I select "Cuba" from dropdown menu with name "country"
    And I type "un text cu orice " on textarea with id "why"
    And I click on button with text "Apply"
    Then I should see an element with text "Field cannot be blank"

  Scenario:  A user that applies to become a distributor leaves empty (the) Surname field
    Given I open url "https://dev:J4g^SqXtk%3@staging.fuel-3d.com/"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    And I click on link with text "Apply To Become A Distributor"
    And I type "Remus" into "First Name *" field
    When I type "abc@gmail.com" into field with id "email2"
    And I type "remussic" into field with id "password2"
    And I select "Cuba" from dropdown menu with name "country"
    And I type "un text cu orice " on textarea with id "why"
    And I click on button with text "Apply"
    Then I should see an element with text "Field cannot be blank"

  Scenario: A user that applies to become a distributor leaves empty (the) Email address field
    Given I open url "https://dev:J4g^SqXtk%3@staging.fuel-3d.com/"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    And I click on link with text "Apply To Become A Distributor"
    And I type "Remus" into "First Name *" field
    And I type "Vescan" into "Surname *" field
    And I type "remussic" into field with id "password2"
    And I select "Cuba" from dropdown menu with name "country"
    And I type "un text cu orice " on textarea with id "why"
    And I click on button with text "Apply"
    Then I should see an element with text "You have not given a correct e-mail address"

  Scenario: A user that applies to become a distributor leaves empty (the) Password  field
    Given I open url "https://dev:J4g^SqXtk%3@staging.fuel-3d.com/"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    And I click on link with text "Apply To Become A Distributor"
    And I type "Remus" into "First Name *" field
    And I type "Vescan" into "Surname *" field
    When I type "abc@gmail.com" into field with id "email2"
    And I select "Cuba" from dropdown menu with name "country"
    And I type "un text cu orice " on textarea with id "why"
    And I click on button with text "Apply"
    Then I should see an element with text "The input value is shorter than 6 characters"

  Scenario: A user that applies to become a distributor leaves empty (the) Country field
    Given I open url "https://dev:J4g^SqXtk%3@staging.fuel-3d.com/"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    And I click on link with text "Apply To Become A Distributor"
    And I type "Remus" into "First Name *" field
    And I type "Vescan" into "Surname *" field
    When I type "abc@gmail.com" into field with id "email2"
    And I type "remussic" into field with id "password2"
    And I type "un text cu orice " on textarea with id "why"
    And I click on button with text "Apply"
    Then I should see an element with text "Field cannot be blank"

  Scenario: A user that applies to become a distributor leaves empty (the) DESCRIBE WHY YOU WANT TO BE A DISTRIBUTOR  field
    Given I open url "https://dev:J4g^SqXtk%3@staging.fuel-3d.com/"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    And I click on link with text "Apply To Become A Distributor"
    And I type "Remus" into "First Name *" field
    And I type "Vescan" into "Surname *" field
    When I type "abc@gmail.com" into field with id "email2"
    And I type "remussic" into field with id "password2"
    And I select "Cuba" from dropdown menu with name "country"
    And I click on button with text "Apply"
    Then I should see an element with text "The input value must be between 1-250 characters"

  Scenario: Applying to be a distributor and leaves empty all fields
    Given I open url "https://dev:J4g^SqXtk%3@staging.fuel-3d.com/"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    And I click on link with text "Apply To Become A Distributor"
    And I click on button with text "Apply"
    Then I should see an element with text "Field cannot be blank"
    And I should see an element with text "You have not given a correct e-mail address"
    And I should see an element with text "The input value is shorter than 6 characters"
    And I should see an element with text "The input value must be between 1-250 characters"


  Scenario: Place an order as a distributor
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with deep text "Place an order"
    And I click on link with text "Order"
    And I type "any first name" into field with id "billing_first_name"
    And I type "any last name" into field with id "billing_last_name"
    And I type "any company" into field with id "billing_company"
    And I type "any address1" into field with id "billing_address_1"
    And I type "any address2" on textarea with id "billing_address_2"
    And I type "any city" on textarea with id "billing_city"
    And I type "any state" into field with id "billing_state"
    And I type "ox3 8js" into field with id "billing_postcode"
    And I type "vescan.remus30@gmail.com" into field with id "billing_email"
    And I type "0752801666" into field with id "billing_phone"
    When I type "any word" on textarea with id "order_comments"
    And I type "4242424242424242" into field with id "stripe-card-number"
    And I type "1027" into field with id "stripe-card-expiry"
    And I type "1234" into field with id "stripe-card-cvc"
    And I click on terms checkbox
    When I click on link with text "Calculate Deposit"
    When I click on link with text "Pay Deposit + Shipping Now"
    And I wait 40 seconds

  Scenario: Place an order as a distributor and leaves empty First Name field
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with deep text "Place an order"
    And I click on link with text "Order"
    And I type "any last name" into field with id "billing_last_name"
    And I type "any company" into field with id "billing_company"
    And I type "any address1" into field with id "billing_address_1"
    And I type "any address2" on textarea with id "billing_address_2"
    And I type "any city" on textarea with id "billing_city"
    And I type "any state" into field with id "billing_state"
    And I type "ox3 8js" into field with id "billing_postcode"
    And I type "vescan.remus30@gmail.com" into field with id "billing_email"
    And I type "0752801666" into field with id "billing_phone"
    When I type "any word" on textarea with id "order_comments"
    And I type "4242424242424242" into field with id "stripe-card-number"
    And I type "1027" into field with id "stripe-card-expiry"
    And I type "1234" into field with id "stripe-card-cvc"
    And I click on terms checkbox
    When I click on link with text "Calculate Deposit"
    When I click on link with text "Pay Deposit + Shipping Now"
    Then I should see an element with text "Field cannot be blank"

  Scenario: Place a order as a distributor and leaves  empty Last Name field
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with deep text "Place an order"
    And I click on link with text "Order"
    And I type "any first name" into field with id "billing_first_name"
    And I type "any company" into field with id "billing_company"
    And I type "any address1" into field with id "billing_address_1"
    And I type "any address2" on textarea with id "billing_address_2"
    And I type "any city" on textarea with id "billing_city"
    And I type "any state" into field with id "billing_state"
    And I type "ox3 8js" into field with id "billing_postcode"
    And I type "vescan.remus30@gmail.com" into field with id "billing_email"
    And I type "0752801666" into field with id "billing_phone"
    When I type "any word" on textarea with id "order_comments"
    And I type "4242424242424242" into field with id "stripe-card-number"
    And I type "1027" into field with id "stripe-card-expiry"
    And I type "1234" into field with id "stripe-card-cvc"
    And I click on terms checkbox
    When I click on link with text "Calculate Deposit"
    When I click on link with text "Pay Deposit + Shipping Now"
    Then I should see an element with text "Field cannot be blank"

  Scenario: Place a order as a distributor  and leaves  empty Address field
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with deep text "Place an order"
    And I click on link with text "Order"
    And I type "any first name" into field with id "billing_first_name"
    And I type "any last name" into field with id "billing_last_name"
    And I type "any company" into field with id "billing_company"
    And I type "any address2" on textarea with id "billing_address_2"
    And I type "any city" on textarea with id "billing_city"
    And I type "any state" into field with id "billing_state"
    And I type "ox3 8js" into field with id "billing_postcode"
    And I type "vescan.remus30@gmail.com" into field with id "billing_email"
    And I type "0752801666" into field with id "billing_phone"
    When I type "any word" on textarea with id "order_comments"
    And I type "4242424242424242" into field with id "stripe-card-number"
    And I type "1027" into field with id "stripe-card-expiry"
    And I type "1234" into field with id "stripe-card-cvc"
    And I click on terms checkbox
    When I click on link with text "Calculate Deposit"
    When I click on link with text "Pay Deposit + Shipping Now"
    Then I should see an element with text "Field cannot be blank"

  Scenario: Place a order as a distributor and leaves empty Town / City field
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with deep text "Place an order"
    And I click on link with text "Order"
    And I type "any first name" into field with id "billing_first_name"
    And I type "any last name" into field with id "billing_last_name"
    And I type "any company" into field with id "billing_company"
    And I type "any address1" into field with id "billing_address_1"
    And I type "any address2" on textarea with id "billing_address_2"
    And I type "any state" into field with id "billing_state"
    And I type "ox3 8js" into field with id "billing_postcode"
    And I type "vescan.remus30@gmail.com" into field with id "billing_email"
    And I type "0752801666" into field with id "billing_phone"
    When I type "any word" on textarea with id "order_comments"
    And I type "4242424242424242" into field with id "stripe-card-number"
    And I type "1027" into field with id "stripe-card-expiry"
    And I type "1234" into field with id "stripe-card-cvc"
    And I click on terms checkbox
    When I click on link with text "Calculate Deposit"
    When I click on link with text "Pay Deposit + Shipping Now"
    Then I should see an element with text "Field cannot be blank"
    And I wait 15 seconds

  Scenario: Place a order as a distributor  and leaves empty Postcode field
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with deep text "Place an order"
    And I click on link with text "Order"
    And I type "any first name" into field with id "billing_first_name"
    And I type "any last name" into field with id "billing_last_name"
    And I type "any company" into field with id "billing_company"
    And I type "any address1" into field with id "billing_address_1"
    And I type "any address2" on textarea with id "billing_address_2"
    And I type "any city" on textarea with id "billing_city"
    And I type "any state" into field with id "billing_state"
    And I type "vescan.remus30@gmail.com" into field with id "billing_email"
    And I type "0752801666" into field with id "billing_phone"
    When I type "any word" on textarea with id "order_comments"
    And I type "4242424242424242" into field with id "stripe-card-number"
    And I type "1027" into field with id "stripe-card-expiry"
    And I type "1234" into field with id "stripe-card-cvc"
    And I click on terms checkbox
    When I click on link with text "Calculate Deposit"
    When I click on link with text "Pay Deposit + Shipping Now"
    Then I should see an element with text "Field cannot be blank"

  Scenario: Place a order as a distributor and leaves empty Phone field
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with deep text "Place an order"
    And I click on link with text "Order"
    And I type "any first name" into field with id "billing_first_name"
    And I type "any last name" into field with id "billing_last_name"
    And I type "any company" into field with id "billing_company"
    And I type "any address1" into field with id "billing_address_1"
    And I type "any address2" on textarea with id "billing_address_2"
    And I type "any city" on textarea with id "billing_city"
    And I type "any state" into field with id "billing_state"
    And I type "ox3 8js" into field with id "billing_postcode"
    And I type "vescan.remus30@gmail.com" into field with id "billing_email"
    When I type "any word" on textarea with id "order_comments"
    And I type "4242424242424242" into field with id "stripe-card-number"
    And I type "1027" into field with id "stripe-card-expiry"
    And I type "1234" into field with id "stripe-card-cvc"
    And I click on terms checkbox
    When I click on link with text "Calculate Deposit"
    When I click on link with text "Pay Deposit + Shipping Now"
    Then I should see an element with text "The input value was not a correct number"


  Scenario: Place a order as a distributor and leaves empty Card Number field
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with deep text "Place an order"
    And I click on link with text "Order"
    And I type "any first name" into field with id "billing_first_name"
    And I type "any last name" into field with id "billing_last_name"
    And I type "any company" into field with id "billing_company"
    And I type "any address1" into field with id "billing_address_1"
    And I type "any address2" on textarea with id "billing_address_2"
    And I type "any city" on textarea with id "billing_city"
    And I type "any state" into field with id "billing_state"
    And I type "ox3 8js" into field with id "billing_postcode"
    And I type "vescan.remus30@gmail.com" into field with id "billing_email"
    And I type "0752801666" into field with id "billing_phone"
    When I type "any word" on textarea with id "order_comments"
    And I type "1027" into field with id "stripe-card-expiry"
    And I type "1234" into field with id "stripe-card-cvc"
    And I click on terms checkbox
    When I click on link with text "Calculate Deposit"
    When I click on link with text "Pay Deposit + Shipping Now"
    Then I should see an element with text "This card number looks invalid."

  Scenario: Place a order as a distributor and leaves empty Expiry (MM/YY) field
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with deep text "Place an order"
    And I click on link with text "Order"
    And I type "any first name" into field with id "billing_first_name"
    And I type "any last name" into field with id "billing_last_name"
    And I type "any company" into field with id "billing_company"
    And I type "any address1" into field with id "billing_address_1"
    And I type "any address2" on textarea with id "billing_address_2"
    And I type "any city" on textarea with id "billing_city"
    And I type "any state" into field with id "billing_state"
    And I type "ox3 8js" into field with id "billing_postcode"
    And I type "vescan.remus30@gmail.com" into field with id "billing_email"
    And I type "0752801666" into field with id "billing_phone"
    When I type "any word" on textarea with id "order_comments"
    And I type "4242424242424242" into field with id "stripe-card-number"
    And I type "1234" into field with id "stripe-card-cvc"
    And I click on terms checkbox
    When I click on link with text "Calculate Deposit"
    When I click on link with text "Pay Deposit + Shipping Now"
    Then I should see an element with text "Your card's expiration year is invalid."


  Scenario: Place a order as a distributor and leaves empty Card Code field
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with deep text "Place an order"
    And I click on link with text "Order"
    And I type "any first name" into field with id "billing_first_name"
    And I type "any last name" into field with id "billing_last_name"
    And I type "any company" into field with id "billing_company"
    And I type "any address1" into field with id "billing_address_1"
    And I type "any address2" on textarea with id "billing_address_2"
    And I type "any city" on textarea with id "billing_city"
    And I type "any state" into field with id "billing_state"
    And I type "ox3 8js" into field with id "billing_postcode"
    And I type "vescan.remus30@gmail.com" into field with id "billing_email"
    And I type "0752801666" into field with id "billing_phone"
    When I type "any word" on textarea with id "order_comments"
    And I type "4242424242424242" into field with id "stripe-card-number"
    And I type "1027" into field with id "stripe-card-expiry"
    And I click on terms checkbox
    When I click on link with text "Calculate Deposit"
    When I click on link with text "Pay Deposit + Shipping Now"
    Then I should see an element with text "Your card's security code is invalid."

  Scenario: Place a order as a distributor and  terms checkbox is not checked
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with deep text "Place an order"
    And I click on link with text "Order"
    And I type "any first name" into field with id "billing_first_name"
    And I type "any last name" into field with id "billing_last_name"
    And I type "any company" into field with id "billing_company"
    And I type "any address1" into field with id "billing_address_1"
    And I type "any address2" on textarea with id "billing_address_2"
    And I type "any city" on textarea with id "billing_city"
    And I type "any state" into field with id "billing_state"
    And I type "ox3 8js" into field with id "billing_postcode"
    And I type "vescan.remus30@gmail.com" into field with id "billing_email"
    And I type "0752801666" into field with id "billing_phone"
    When I type "any word" on textarea with id "order_comments"
    And I type "4242424242424242" into field with id "stripe-card-number"
    And I type "1027" into field with id "stripe-card-expiry"
    And I type "1234" into field with id "stripe-card-cvc"
    When I click on link with text "Calculate Deposit"
    When I click on link with text "Pay Deposit + Shipping Now"
    Then I should see an element with text "You must accept our Terms & Conditions."

  Scenario: Place a order as a distributor and leave all fields empty
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with deep text "Place an order"
    And I click on link with text "Order"
    When I click on link with text "Calculate Deposit"
    When I click on link with text "Pay Deposit + Shipping Now"

  Scenario: Distributor and edit profile
    Given I open url "https://dev:J4g^SqXtk%3@dev.fuel-3d.com"
    And I mouse over on element with text "Fuel3D Store"
    And I click on link with text "Distributor portal"
    When I type "distributor" on textarea with id "email"
    When I type "123456" on textarea with id "password"
    And I click on button with text "Login"
    And I click on link with text "Edit profile"
    And I type "JOHN" into field with name "first-name"
    And I type "Samuel" into field with name "last-name"
    And I type "SOHN" into field with id "billing_first_name"
    And I type "Samuel" into field with id "billing_last_name"
    And I type "Any company" into field with id "billing_company"
    And I type "Any address" into field with id "billing_address_1"
    And I type "Any apartment " into field with id "billing_address_2"
    And I type "Oxford" into field with id "billing_city"
    And I type "England" into field with id "billing_state"
    And I type "ox3 8js" into field with id "billing_postcode"
    And I type "tudor+dist13942@experiencematter.co.uk" into field with id "billing_email"
    And I type "0752801666" into field with id "billing_phone"
    And I type "tudor+dist13942@experiencematter.co.uk" into field with id "email"
    And I type "123456" into field with id "pass1"
    And I type "123456" into field with id "pass2"
    And I type "JOHN" into field with name "shipping_first_name"
    And I type "Samuel" into field with name "shipping_last_name"
    And I type "Any company" into field with id "shipping_company"
    And I type "Any address" into field with id "shipping_address_1"
    And I type "Any apartment " into field with id "shipping_address_2"
    And I type "Oxford" into field with id "shipping_city"
    And I type "England" into field with id "shipping_state"
    And I type "ox3 8js" into field with id "shipping_postcode"
    And I click on link with text "Back to portal"

